# Action used to build and push the wheel using
# Github Actions
#
# @author Stavros Grigoriou <unix121@protonmail.com>
on:
  push:
    branches:
      - '**'

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Format code using yapf
        run: |
          pip install --upgrade yapf
          
          yapf airgoodies/ -r -i
      - name: Build wheel and install
        run: |
          pip install --upgrade setuptools
          pip install --upgrade wheel
          
          python setup.py sdist bdist_wheel
          
          find ./dist/*.whl | xargs pip install
      - name: Run tests
        run: |
          python -m unittest